# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Aljabar Linear Elementer  # Judul di sidebar
author: Lutfi                   # Nama kamu sebagai penulis
logo: images/logo.png           # Pastikan file ada di folder images

# Pengaturan Eksekusi Notebook
execute:
  execute_notebooks: cache      # Menggunakan cache agar proses build lebih cepat

# Pengaturan PDF (Opsional)
latex:
  latex_documents:
    targetname: buku_kal.tex

# File Referensi/Sitasi
bibtex_bibfiles:
  - references.bib

# Informasi Repository GitHub
repository:
  url: https://github.com/Lutttfi/kal  # Link repo kamu
  path_to_book: .                      # Titik karena file ada di root folder
  branch: main                         # Sudah disesuaikan ke 'main'

# Pengaturan Tampilan HTML (Estetika)
html:
  favicon: images/favicon.png          # Ikon di tab browser
  use_issues_button: true              # Tombol lapor error
  use_repository_button: true          # Tombol ke repo GitHub
  use_edit_page_button: false          # Matikan jika tidak ingin orang lain edit
  home_page_in_toc: true               # Menampilkan 'Intro' di daftar isi
  navbar_footer_text: "Dibuat dengan ❤️ oleh Lutfi" # Teks di bawah menu
  announcement: "Selamat datang di Modul Digital Aljabar Linear!" # Pesan di atas web